### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [seanysean/LearnChess#2]
Hello! @seanysean 

I am a graphic designer and i like contribute to opensource sofwares. I designed a logo for learnchess. Please tell me what you think. I will wait for feedback.

Have a nice day!

![learnchess](https://user-images.githubusercontent.com/36298335/43688657-78de47a2-98f5-11e8-8765-b54221e5cfa5.jpg)

**Comment by seanysean** [comment]
Hello! @reallinfo 

First, thank you for creating the logo! I appreciate the time you took designing it.

I like the idea, but unfortunately your logo doesn't work quite right on 16x16px favicons (squares are too small): <img src="https://user-images.githubusercontent.com/24863887/43727113-7417392c-9977-11e8-9b4b-ad2513441baa.png" height="16px" width="16px">. Maybe it would look better with fewer squares.

I should mention that you don't need to add the LearnChess text, I just need the icon. As for colors, just stick to monochrome with the light chessboard squares being transparent, if possible. That will enable me to possibly use it as a font.

Thanks again for the design!

**Comment by reallinfo** [comment]
You're welcome. Okay, I will send you a few samples as soon as possible.

**Comment by reallinfo** [comment]
Hi again, I made the logo more minimalist. White squares are transparent in all options. Which option is exactly  what you want?

![1](https://user-images.githubusercontent.com/36298335/43956626-9adef4f8-9cad-11e8-8e3f-1c9fadce47a6.jpg)

**Comment by seanysean** [comment]
I really like the first one. One last thing I forgot to mention last time - could you export it in SVG format :) ? Then I could change colors as needed for different places.
Just make a PR adding all of the files to public_html/images, and I will create a thanks page on the site with a link to your GitHub profile (unless you would prefer something else).

Thank you very much ! I'm very happy it looks good at 16x16px: <img src="https://user-images.githubusercontent.com/24863887/43980933-4a3a1578-9cc6-11e8-92bd-9fbb7362b1a8.PNG" height="16px" width="16px">.

**Comment by reallinfo** [comment]
Sure, I sent a pr.  If there is any problem, feel free to say me.
